///|
pub typealias (A) -> B as Arrow[A, B]

///|
pub typealias (A) -> (B) -> C as Arrow2[A, B, C]

///|
pub typealias (A) -> (B) -> (C) -> D as Arrow3[A, B, C, D]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> E as Arrow4[A, B, C, D, E]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> F as Arrow5[A, B, C, D, E, F]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> G as
Arrow6[A, B, C, D, E, F, G]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> H as
Arrow7[A, B, C, D, E, F, G, H]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> I as
Arrow8[A, B, C, D, E, F, G, H, I]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> J as
Arrow9[A, B, C, D, E, F, G, H, I, J]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> K as
Arrow10[A, B, C, D, E, F, G, H, I, J, K]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> L as Arrow11[A, B, C, D, E, F, G, H, I, J, K, L]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> M as Arrow12[A, B, C, D, E, F, G, H, I, J, K, L, M]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> N as Arrow13[A, B, C, D, E, F, G, H, I, J, K, L, M, N]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> O as
Arrow14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> P as
Arrow15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> Q as
Arrow16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> R as
Arrow17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> S as
Arrow18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> T as
Arrow19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> U as
Arrow20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> V as
Arrow21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> W as
Arrow22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (
  W,
) -> X as
Arrow23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (
  W,
) -> (X) -> Y as
Arrow24[
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
]

///|
pub typealias (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (
  K,
) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (
  W,
) -> (X) -> (Y) -> Z as
Arrow25[
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
]
