///|
pub typealias Arrow[A, B] = (A) -> B

///|
pub typealias Arrow2[A, B, C] = (A) -> (B) -> C

///|
pub typealias Arrow3[A, B, C, D] = (A) -> (B) -> (C) -> D

///|
pub typealias Arrow4[A, B, C, D, E] = (A) -> (B) -> (C) -> (D) -> E

///|
pub typealias Arrow5[A, B, C, D, E, F] = (A) -> (B) -> (C) -> (D) -> (E) -> F

///|
pub typealias Arrow6[A, B, C, D, E, F, G] = (A) -> (B) -> (C) -> (D) -> (E) -> (
  F,
) -> G

///|
pub typealias Arrow7[A, B, C, D, E, F, G, H] = (A) -> (B) -> (C) -> (D) -> (E) -> (
  F,
) -> (G) -> H

///|
pub typealias Arrow8[A, B, C, D, E, F, G, H, I] = (A) -> (B) -> (C) -> (D) -> (
  E,
) -> (F) -> (G) -> (H) -> I

///|
pub typealias Arrow9[A, B, C, D, E, F, G, H, I, J] = (A) -> (B) -> (C) -> (D) -> (
  E,
) -> (F) -> (G) -> (H) -> (I) -> J

///|
pub typealias Arrow10[A, B, C, D, E, F, G, H, I, J, K] = (A) -> (B) -> (C) -> (
  D,
) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> K

///|
pub typealias Arrow11[A, B, C, D, E, F, G, H, I, J, K, L] = (A) -> (B) -> (C) -> (
  D,
) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> L

///|
pub typealias Arrow12[A, B, C, D, E, F, G, H, I, J, K, L, M] = (A) -> (B) -> (C) -> (
  D,
) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> M

///|
pub typealias Arrow13[A, B, C, D, E, F, G, H, I, J, K, L, M, N] = (A) -> (B) -> (
  C,
) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> N

///|
pub typealias Arrow14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] = (A) -> (B) -> (
  C,
) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> O

///|
pub typealias Arrow15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] = (A) -> (
  B,
) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (
  N,
) -> (O) -> P

///|
pub typealias Arrow16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q] = (A) -> (
  B,
) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (
  N,
) -> (O) -> (P) -> Q

///|
pub typealias Arrow17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> R

///|
pub typealias Arrow18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> S

///|
pub typealias Arrow19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> T

///|
pub typealias Arrow20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> U

///|
pub typealias Arrow21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> V

///|
pub typealias Arrow22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> W

///|
pub typealias Arrow23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (W) -> X

///|
pub typealias Arrow24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (W) -> (X) -> Y

///|
pub typealias Arrow25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z] = (
  A,
) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (
  M,
) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> (W) -> (X) -> (
  Y,
) -> Z
